function variables = ccm_min_vars

variables = {...
    'fixWindowEntered',...
    'targOn',...
    'checkerOn',...
    'stopSignalOn',...
    'responseOnset',...
    'toneOn',...
    'rewardOn',...
    'trialOutcome',...
    'targ1CheckerProp',...
    'saccToTargIndex',...
    'targAngle',...
    'saccAngle',...
    'responseCueOn',...
    'SessionData',...
    };